### ISSUE TITLE
Phantom Workflow

### ISSUE THREAD

**Issue by bbonora** [Cecilapp/Cecil-Action#3]
Hello,

Thanks for putting this together. I've really been loving using Cecil and think it's a great static site generator. 

I wanted to use Github Actions to deploy my Cecil site to Github Pages. I cut and pasted the example workflow file contained in the `Readme.md` into my ` .github/workflows` folder on my project but I'm getting strange results. When the action runs I'm seeing two workflows being executed - One is called `Build and deploy to GitHub Pages` and the other is called `pages-build-deploy`. I can't find this workflow anywhere in my workflows file and I think it's building a Jekyll site instead of a Cecil site. Below I've included a screenshot of what I'm seeing along with my workflow file. Any help would be much appreciated.

![image](https://github.com/Cecilapp/Action/assets/1057284/4f51713e-a674-456b-aa19-501856a6c0df)

```
# .github/workflows/website.yml

name: Build and deploy to GitHub Pages
on:
  push:
    branches: [main] # or [master]
  workflow_dispatch: # run manually

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: fileinfo, gd, mbstring

      - name: Build site
        uses: Cecilapp/Cecil-Action@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
```
